### ISSUE TITLE
How to specify frontend_api?

### ISSUE THREAD

**Issue by AlexBulankou** [googleforgames/global-multiplayer-demo#160]
In the demo setup instructions frontend_api should be specified in editor launch parameters as `frontend_api=[IP_ADDRESS]` and in launcher app.ini parameters as `http://[IP_ADDRESS].sslip.io`. 
Confirming if this is intentional or they should be specified consistently? Thanks!

**Comment by markmandel** [comment]
I would specify it consistently as `http://[IP_ADDRESS].sslip.io` so that the domain auth works -- but at the editor level it _probably_ shouldn't matter, since the domain is primarily needed for initial oauth authentication.

We should change the docs to be consistent.
