### ISSUE TITLE
[Unreal] "Waiting for players to join" screen never goes away.

### ISSUE THREAD

**Issue by markmandel** [googleforgames/global-multiplayer-demo#164]
Very occasionally this loading image shows up on one (or more) my clients:

![image](https://user-images.githubusercontent.com/298370/228668829-e6a614ed-f313-4ba0-a640-b8e00bcadc0e.png)

I can still play the game, but it just obstructs the view.

**Comment by kennycoder** [comment]
Found the issue, will fix in the next release.

**Comment by markmandel** [comment]
Bumping in @kennycoder priority queue.

**Comment by kennycoder** [comment]
Tried couple of fixes, but still able to replicate this issue - it appears randomly. Further investigation needed but all points to synchronization issue. Going to resume next week.

**Comment by kennycoder** [comment]
https://github.com/googleforgames/global-multiplayer-demo/pull/182

**Comment by markmandel** [comment]
Closing as fixed!
